sudo: required
language: java
jdk: oraclejdk8
node_js:
- 8.5.0
services:
- docker
install: true
env:
  local:
    maven:
    - repository=$HOME/.m2
    - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  chrome: stable
  sonarcloud:
    organization: processpuzzle
    token:
      secure: "$SONAR_TOKEN"
    branches:
    - development
    - master

before_install:
- openssl aes-256-cbc -K $encrypted_d49bee1cc322_key -iv $encrypted_d49bee1cc322_iv
  -in codesigning.asc.enc -out codesigning.asc -d
- gpg --fast-import codesigning.asc
- nvm install node
- nvm use node
- npm install -g npm@5.5.1
- npm --version
- if [ ${TRAVIS_BRANCH} == development ]; then DEPLOYMENT_ENVIRONMENT=dev; elif [ -n ${TRAVIS_TAG} ]; then DEPLOYMENT_ENVIRONMENT=prod; else DEPLOYMENT_ENVIRONMENT=integ; fi; export DEPLOYMENT_ENVIRONMENT;

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
  - "./img-web/node_modules"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g typescript
  - npm remove -g angular-cli
  - npm uninstall -g @angular/cli
  - npm cache clean --force
  - npm install -g @angular/cli@latest
  - npm install -g @angular/compiler-cli
  - ng --version
  - npm update --prefix ./processpuzzle-cms-ui

script:
  - mvn clean deploy org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar --settings travis-maven-settings.xml -B
  
deploy:
  - provider: elasticbeanstalk
    access_key_id: AKIAJGCDIH623MFPRVEQ
    secret_access_key:
      secure: oX+pp2+eLGk+oLlpBel+4hiJZd7gmPNfFepUBAHajfZTGL6Y/l1g6f4Un5rh+Y22OPiOVhdtAk4xsgzgfzmp4Vfzg6rgdt5TeJWoJ4c2oqXkR5xcDsMJ2Dm5UeHOy+MMKNDaXYuhkvDabpXzEYo/GZc+Lz2xWIkPIHByGOUJG1xNQAZ1Dl63N7Eai/N3e0N0A+VvMi/5V5ELeErO4gDXlSKeuTxaQmU+qkN9MzTN60e8cXByiSZoUoQFAVujqejukzCMPyy3AOHzDqQ3Dgs8xCM9eAjiPYeII7BwsPXDqExjZdKua8T6oBf1aRlHwY2udBcoSyWQidXT4bN6btxxBOmVTepmuDbw7QMF9ysokpBD0oME/7Ef7Eok5oEvfRSMlssCccLZ/rlQMiNmygtGn9pmoim3O9bnzA1q4ceDsO/vzl98bHvRvZ+xH1TwDH8czHwl1x4PQHPdT54ZOy0z2jpsEbhunqqU0UNcWXCYtZIPDdgl9UjW5y39mrtWHdDXs2Fel35BR2zG+qqy7gsIwE539dcteIGkrqQNvNg2Dy1v7Lcw9wfyNkaFedpP+bEWSp7ajLHmW6ndyp/POUhfktpsPdii7XdbHVkkgPHbJsfpj2zTCJRIOr4JxCQA5TLFmo8NR91xS5veUYu1bg0v3LSD5z8cEpJ97xJ5ymaNfIE=
    region: eu-central-1
    app: ProcessPuzzle-Core
    env: dev-env
    bucket_name: processpuzzle-core
    zip_file: "./processpuzzle-core-aws/target/processpuzzle-core.zip"
    upload-dir: processpuzzle-core-aws
    skip_cleanup: true
    on:
      branch: development
  - provider: elasticbeanstalk
    access_key_id: AKIAJGCDIH623MFPRVEQ
    secret_access_key:
      secure: oX+pp2+eLGk+oLlpBel+4hiJZd7gmPNfFepUBAHajfZTGL6Y/l1g6f4Un5rh+Y22OPiOVhdtAk4xsgzgfzmp4Vfzg6rgdt5TeJWoJ4c2oqXkR5xcDsMJ2Dm5UeHOy+MMKNDaXYuhkvDabpXzEYo/GZc+Lz2xWIkPIHByGOUJG1xNQAZ1Dl63N7Eai/N3e0N0A+VvMi/5V5ELeErO4gDXlSKeuTxaQmU+qkN9MzTN60e8cXByiSZoUoQFAVujqejukzCMPyy3AOHzDqQ3Dgs8xCM9eAjiPYeII7BwsPXDqExjZdKua8T6oBf1aRlHwY2udBcoSyWQidXT4bN6btxxBOmVTepmuDbw7QMF9ysokpBD0oME/7Ef7Eok5oEvfRSMlssCccLZ/rlQMiNmygtGn9pmoim3O9bnzA1q4ceDsO/vzl98bHvRvZ+xH1TwDH8czHwl1x4PQHPdT54ZOy0z2jpsEbhunqqU0UNcWXCYtZIPDdgl9UjW5y39mrtWHdDXs2Fel35BR2zG+qqy7gsIwE539dcteIGkrqQNvNg2Dy1v7Lcw9wfyNkaFedpP+bEWSp7ajLHmW6ndyp/POUhfktpsPdii7XdbHVkkgPHbJsfpj2zTCJRIOr4JxCQA5TLFmo8NR91xS5veUYu1bg0v3LSD5z8cEpJ97xJ5ymaNfIE=
    region: eu-central-1
    app: ProcessPuzzle-CMS
    env: prod-env
    bucket_name: processpuzzle-core
    zip_file: "./processpuzzle-core-aws/target/processpuzzle-core.zip"
    upload-dir: processpuzzle-core-aws
    skip_cleanup: true
    on:
      branch: master  
      tags: true
  - provider: releases
    api_key:
      secure: XYnuZULC/Qol43bAWqH6nBzkYtjNnERQq+PppaYtcWaB9sbDJQXBj2MqLF355BFI6IA9FSsx1GLdX5R3+tAJsteWyq6Xrk7WpLDSPdOYhU3BlUCJeU35YQkZ+rPPsHfDzBghTOEH3OxqcmozlUVqvg1JyaZ2fitGBNRuGCPN6k/y7fd3jtOT6BhSPAMIKodr/B+RW+sGfjl+ffFFjFXNIOyBa7Y6LINlJdgr5mJGmVQPsUiJeuVx58nBxuzRbKoX9d/vMbeiLkuFRVqEzmcDptl1MrqcGuVwxPzuT9wCfGSMUN8X/hss74ZTbmeAZ6jjk8xo8QPlqAxr62ChkFeGKRsZhiHcLfc6J7G0+JfY+Wwx/ra3EwBz4kfdZ34HgHy1c83AfuT4zj+UByhr3EXf5Xi+UfT5BcwgvdRsZ6yFw0CtBjukC2Bc5zdrusQzmpEK+S4a8X0jdDpLsDj0oJjuoM1DVEp83TiFah9/4F3c5qYRXHRjkIF46XHivWPhJwYKpWKGo/nUpJCxX0MgCUb+r+RcuxALiARAJmj7ZdcTKNfuSpdxFR4IZjVlR40ASRWJJEMs9cOWIsIjrggVeScFB0quBL/Va2SsCar8+6JaSahQg2LKT9P5lVS6KUNoLu7E7xSkkKvrBApU3awNyd92WygmAA3mIzVCeBD+wW8TZF4=
    file:
    - processpuzzle-core-services/target/processpuzzle-core.zip
    skip_cleanup: true
    on:
      branch: master
      tags: true
      repo: ZsZs/processpuzzle-core
